version: 2
jobs:
  test-deploy-job:
    docker:
      - image: circleci/node:6.10-browsers
    steps:
      - run:
          name: Install dependencies
          command: sudo apt-get -y -qq install awscli
      - checkout
      - run:
          name: Install
          command: npm install
      # - run:
      #     name: Test
      #     command: npm test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy to S3
          command: aws s3 sync ./build s3://cheese.mklowe/ --delete --region=ap-southeast-2
workflows:
  version: 2
  build-deploy:
    jobs:
      - test-deploy-job:
          filters:
            branches:
              only: master